// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0f5WBczYZ9tmlnGkjMLzWNI3oFphe-D8',
    appId: '1:339018358380:web:1a718aa062efaf7ba78249',
    messagingSenderId: '339018358380',
    projectId: 'solar-system-7ffca',
    authDomain: 'solar-system-7ffca.firebaseapp.com',
    storageBucket: 'solar-system-7ffca.appspot.com',
    measurementId: 'G-C31XC1JM4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnqcENHjheLtPNRCb-Q-m4ybt2EXlqe8c',
    appId: '1:339018358380:android:30b08cc3a587a396a78249',
    messagingSenderId: '339018358380',
    projectId: 'solar-system-7ffca',
    storageBucket: 'solar-system-7ffca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3f7PJyg5RaWhZ1E-EbIoTJ4bTFWTZCjo',
    appId: '1:339018358380:ios:7fb9ad7f57957b7ca78249',
    messagingSenderId: '339018358380',
    projectId: 'solar-system-7ffca',
    storageBucket: 'solar-system-7ffca.appspot.com',
    iosClientId: '339018358380-hsjt5tehbblium2a6mjkvi59smd4llvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarSystem',
  );
}
